version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - $DB_PORT:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn start:dev'
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - $BACKEND_PORT:3000
      - $PRISMA_STUDIO_PORT:5555
    environment:
      - NODE_ENV=development
    tty: true
    depends_on:
      - db

volumes:
  db_data:
  backend_node_modules:
